name: Deploy Axora Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements_pyqt6.txt
        
    - name: Build macOS app
      run: python3 build_macos.py
      
    - name: Create Windows placeholder
      run: |
        mkdir -p downloads
        echo "Windows executable coming soon!" > downloads/Axora-Windows.exe
        
    - name: Copy website files
      run: |
        cp index.html downloads/
        cp QUICK_START.md downloads/
        cp INSTALLATION_GUIDE.md downloads/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./downloads
        cname: axora.com  # Replace with your custom domain or remove this line